AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  DataHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lumigo_tracer._handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role: 'arn:aws:iam::REDACTED:role/service-role/LumigoRole'
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue:
              'Fn::GetAtt':
                - SQSQueue1
                - Arn
            BatchSize: 10
      Environment:
        Variables:
          LUMIGO_ORIGINAL_HANDLER: REDACTED
          LUMIGO_TRACER_TOKEN: REDACTED
      Layers:
        - >-
          arn:aws:lambda:ap-southeast-1:REDACTED:layer:lumigo-python-tracer:224
  SQSQueue1:
    Type: 'AWS::SQS::Queue'
    Properties: {}
